"""Generate the bundled presets/default_library.json file.

This is a build-time script that emits the complete starter library
described in the project spec. The output is deterministic and
re-validated by ``scripts/validate_library.py``.

Run from the project root:

    python3 scripts/build_default_library.py

The output is written to ``presets/default_library.json``.
"""
from __future__ import annotations

import json
import os
import sys

# Ensure the src package is importable.
THIS_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(THIS_DIR)
sys.path.insert(0, ROOT)

from src.schemas import (
    MODE_BIPOLAR,
    MODE_RAW,
    MODE_SCALAR,
    PROFILE_GENERIC,
    PROFILE_KREA_RAW,
    PROFILE_KREA_TURBO,
    SCHEMA_VERSION,
    SLIDER_DEFAULT,
    VERIFICATION_COMMUNITY,
    VERIFICATION_DEPRECATED,
    VERIFICATION_GENERAL,
    VERIFICATION_LOCAL,
    VERIFICATION_UNRELIABLE,
)


# ---------------------------------------------------------------------------
# Preset table
# ---------------------------------------------------------------------------

PRESETS = [
    # -------------------- EMOTION --------------------
    ("emotion", "Joy", "joy", 65, ["delight", "glee"]),
    ("emotion", "Happiness", "happiness", 65, ["happy", "joyful"]),
    ("emotion", "Amusement", "amusement", 60, ["playful", "entertained"]),
    ("emotion", "Contentment", "contentment", 55, ["serene contentment", "satisfied"]),
    ("emotion", "Excitement", "excitement", 70, ["thrilled", "pumped"]),
    ("emotion", "Elation", "elation", 75, ["euphoric", "exhilarated"]),
    ("emotion", "Relief", "relief", 55, ["unburdened", "at ease"]),
    ("emotion", "Serenity", "serenity", 60, ["calm", "tranquil"]),
    ("emotion", "Affection", "affection", 60, ["loving", "tender warmth"]),
    ("emotion", "Tenderness", "tenderness", 55, ["gentle loving", "soft-hearted"]),
    ("emotion", "Pride", "pride", 60, ["dignified pride", "accomplished"]),
    ("emotion", "Hope", "hope", 60, ["hopeful", "optimistic"]),
    ("emotion", "Wonder", "wonder", 65, ["wonderment", "amazement"]),
    ("emotion", "Awe", "awe", 70, ["awestruck", "breathless awe"]),
    ("emotion", "Surprise", "surprise", 60, ["surprised", "caught off guard"]),
    ("emotion", "Shock", "shocked expression", 75, ["shocked", "startled"]),
    ("emotion", "Confusion", "confusion", 60, ["confused", "puzzled"]),
    ("emotion", "Curiosity", "curiosity", 60, ["curious", "inquisitive"]),
    ("emotion", "Skepticism", "skepticism", 55, ["skeptical", "doubtful"]),
    ("emotion", "Suspicion", "suspicion", 60, ["suspicious", "wary"]),
    ("emotion", "Uncertainty", "uncertainty", 55, ["unsure", "tentative"]),
    ("emotion", "Anxiety", "anxiety", 60, ["anxious", "on edge"]),
    ("emotion", "Nervousness", "nervousness", 55, ["nervous", "skittish"]),
    ("emotion", "Fear", "fear", 70, ["afraid", "scared"]),
    ("emotion", "Terror", "terror", 80, ["terrified", "horrified"]),
    ("emotion", "Panic", "panic", 80, ["panicked", "hysterical"]),
    ("emotion", "Sadness", "sadness", 65, ["sad", "sorrowful"]),
    ("emotion", "Melancholy", "melancholy", 60, ["wistful melancholy", "pensive"]),
    ("emotion", "Grief", "grief", 75, ["deep grief", "mournful"]),
    ("emotion", "Despair", "despair", 75, ["despondent", "hopeless"]),
    ("emotion", "Loneliness", "loneliness", 65, ["lonely", "isolated"]),
    ("emotion", "Disappointment", "disappointment", 60, ["let down", "sigh"]),
    ("emotion", "Embarrassment", "embarrassment", 60, ["embarrassed", "flustered"]),
    ("emotion", "Shame", "shame", 65, ["ashamed", "humiliated"]),
    ("emotion", "Guilt", "guilt", 65, ["guilty", "remorseful"]),
    ("emotion", "Anger", "anger", 65, ["angry", "mad"]),
    ("emotion", "Irritation", "irritation", 55, ["irritated", "annoyed"]),
    ("emotion", "Frustration", "frustration", 60, ["frustrated", "exasperated"]),
    ("emotion", "Fury", "fury", 75, ["furious", "enraged"]),
    ("emotion", "Rage", "rage", 80, ["raging", "incandescent"]),
    ("emotion", "Defiance", "defiance", 65, ["defiant", "rebellious"]),
    ("emotion", "Determination", "determination", 65, ["determined", "resolute"]),
    ("emotion", "Disgust", "disgust", 65, ["disgusted", "repulsed"]),
    ("emotion", "Contempt", "contempt", 60, ["contemptuous", "scornful"]),
    ("emotion", "Boredom", "boredom", 55, ["bored", "apathetic"]),
    ("emotion", "Fatigue", "fatigue", 55, ["exhausted", "weary"]),
    ("emotion", "Emotional numbness", "emotional numbness", 60, ["numb", "hollow"]),
    # -------------------- FACIAL ACTIONS --------------------
    ("face", "Inner brow raiser", "inner brow raiser", 55, ["raised inner brows"]),
    ("face", "Outer brow raiser", "outer brow raiser", 55, ["raised outer brows"]),
    ("face", "Left outer brow raiser", "left outer brow raiser", 55, ["single raised brow"]),
    ("face", "Right outer brow raiser", "right outer brow raiser", 55, ["single raised brow"]),
    ("face", "Brow lowerer", "brow lowerer", 60, ["furrowed brow"]),
    ("face", "Upper eyelid raiser", "raised upper eyelids", 55, ["wide open eyes"]),
    ("face", "Cheek raiser", "cheek raiser", 55, ["raised cheeks"]),
    ("face", "Eyelid tightener", "tightened eyelids", 55, ["squinted eyes"]),
    ("face", "Nose wrinkler", "nose wrinkler", 55, ["wrinkled nose"]),
    ("face", "Upper lip raiser", "raised upper lip", 55, ["snarl"]),
    ("face", "Lip corner puller", "lip corner puller", 55, ["smile"]),
    ("face", "Dimpler", "dimpler", 50, ["cheek dimple"]),
    ("face", "Lip corner depressor", "lip corner depressor", 55, ["frown"]),
    ("face", "Chin raiser", "raised chin", 55, ["proud chin"]),
    ("face", "Lip stretcher", "lip stretcher", 50, ["taut lips"]),
    ("face", "Lip tightener", "tightened lips", 50, ["compressed lips"]),
    ("face", "Lip pressor", "lip pressor", 50, ["pressed lips"]),
    ("face", "Lips part", "parted lips", 50, ["slightly open lips"]),
    ("face", "Jaw drop", "jaw drop", 55, ["dropped jaw"]),
    ("face", "Mouth stretch", "mouth stretch", 50, ["stretched mouth"]),
    ("face", "Lip suck", "lip suck", 50, ["lips drawn inward"]),
    ("face", "One eyebrow raised", "one eyebrow raised", 55, ["single raised brow"]),
    ("face", "Furrowed brow", "furrowed brow", 60, ["knitted brow"]),
    ("face", "Tensed lower eyelids", "tensed lower eyelids", 55, ["bag-free eyes"]),
    ("face", "Tear-filled eyes", "tear-filled eyes", 70, ["glistening eyes"]),
    ("face", "Flared nostrils", "flared nostrils", 55, ["wide nostrils"]),
    ("face", "Clenched jaw", "clenched jaw", 55, ["tight jaw"]),
    ("face", "Visible teeth", "visible teeth", 50, ["showing teeth"]),
    ("face", "Wrinkled forehead", "wrinkled forehead", 55, ["lined forehead"]),
    # -------------------- MOUTH / VOCAL --------------------
    ("mouth", "Gentle smile", "gentle smile", 55, ["soft smile"]),
    ("mouth", "Broad smile", "broad smile", 60, ["wide smile"]),
    ("mouth", "Grin", "grin", 60, ["tooth-showing grin"]),
    ("mouth", "Smirk", "smirk", 55, ["one-sided smirk"]),
    ("mouth", "Laughing", "laughing", 65, ["laughing expression"]),
    ("mouth", "Open-mouth laughter", "open-mouth laughter", 70, ["roaring laugh"]),
    ("mouth", "Shouting", "shouting", 65, ["yelling", "open mouth shout"]),
    ("mouth", "Screaming", "screaming", 70, ["scream"]),
    ("mouth", "Whispering", "whispering", 55, ["quiet whisper"]),
    ("mouth", "Gasping", "gasping", 65, ["sharp gasp"]),
    ("mouth", "Crying", "crying", 75, ["sobbing cry"]),
    ("mouth", "Sobbing", "sobbing", 75, ["deep sobbing"]),
    ("mouth", "Parted lips", "parted lips", 50, ["slightly parted"]),
    ("mouth", "Pursed lips", "pursed lips", 50, ["puckered lips"]),
    ("mouth", "Compressed lips", "compressed lips", 50, ["pressed lips"]),
    ("mouth", "Clenched teeth", "clenched teeth", 55, ["gritted teeth"]),
    ("mouth", "Biting lower lip", "biting lower lip", 55, ["lip bite"]),
    ("mouth", "Open mouth", "open mouth", 55, ["mouth agape"]),
    ("mouth", "Jaw dropped", "dropped jaw", 55, ["jaw slack"]),
    ("mouth", "Tongue slightly visible", "tongue slightly visible", 50, ["peek of tongue"]),
    # -------------------- GAZE --------------------
    ("gaze", "Looking directly into the camera", "looking directly into the camera", 60, ["direct gaze"]),
    ("gaze", "Looking slightly off camera", "looking slightly off camera", 55, ["subtle off-camera gaze"]),
    ("gaze", "Side glance", "side glance", 55, ["glancing sideways"]),
    ("gaze", "Looking upward", "looking upward", 55, ["looking up"]),
    ("gaze", "Looking downward", "looking downward", 55, ["looking down"]),
    ("gaze", "Looking over shoulder", "looking over shoulder", 60, ["over-shoulder glance"]),
    ("gaze", "Eyes closed", "eyes closed", 55, ["shut eyes"]),
    ("gaze", "Eyes half closed", "eyes half closed", 55, ["drowsy eyes"]),
    ("gaze", "Squinting", "squinting", 55, ["narrowed eyes"]),
    ("gaze", "Wide open eyes", "wide open eyes", 60, ["enlarged eyes"]),
    ("gaze", "Fixed intense stare", "fixed intense stare", 65, ["staring intently"]),
    ("gaze", "Avoiding eye contact", "avoiding eye contact", 55, ["averted gaze"]),
    ("gaze", "Looking toward another subject", "looking toward another subject", 55, ["looking at someone"]),
    ("gaze", "Looking into the distance", "looking into the distance", 55, ["distant gaze"]),
    ("gaze", "Eyes focused on a nearby object", "eyes focused on a nearby object", 55, ["focused on object"]),
    # -------------------- BODY / POSE --------------------
    ("body", "Relaxed posture", "relaxed posture", 55, ["loose posture"]),
    ("body", "Tense posture", "tense posture", 55, ["tight posture"]),
    ("body", "Open posture", "open posture", 55, ["exposed posture"]),
    ("body", "Closed posture", "closed posture", 55, ["guarded posture"]),
    ("body", "Hunched shoulders", "hunched shoulders", 55, ["rolled shoulders"]),
    ("body", "Shoulders pulled back", "shoulders pulled back", 55, ["square shoulders"]),
    ("body", "Leaning forward", "leaning forward", 55, ["forward lean"]),
    ("body", "Leaning backward", "leaning backward", 55, ["reclined lean"]),
    ("body", "Recoiling", "recoiling", 60, ["flinching"]),
    ("body", "Twisting torso", "twisting torso", 55, ["torso twist"]),
    ("body", "Arms crossed", "arms crossed", 55, ["folded arms"]),
    ("body", "Arms open", "arms open", 55, ["open arms"]),
    ("body", "Clenched fists", "clenched fists", 55, ["tight fists"]),
    ("body", "Hands raised", "hands raised", 55, ["raised hands"]),
    ("body", "Hands covering face", "hands covering face", 60, ["facepalm"]),
    ("body", "Reaching toward camera", "reaching toward camera", 60, ["outstretched hand"]),
    ("body", "Pointing", "pointing", 55, ["aiming finger"]),
    ("body", "Crouching", "crouching", 55, ["low crouch"]),
    ("body", "Kneeling", "kneeling", 55, ["on knees"]),
    ("body", "Sitting", "sitting", 55, ["seated"]),
    ("body", "Running", "running", 60, ["mid-run"]),
    ("body", "Walking", "walking", 55, ["mid-stride"]),
    ("body", "Jumping", "jumping", 60, ["mid-air"]),
    ("body", "Falling", "falling", 65, ["falling pose"]),
    ("body", "Turning quickly", "turning quickly", 55, ["whipping turn"]),
    ("body", "Standing rigidly", "standing rigidly", 55, ["rigid stance"]),
    ("body", "Protective stance", "protective stance", 55, ["guarded stance"]),
    ("body", "Confident stance", "confident stance", 55, ["assertive posture"]),
    ("body", "Defensive stance", "defensive stance", 55, ["cautious posture"]),
    ("body", "Exhausted posture", "exhausted posture", 55, ["drooped posture"]),
    # -------------------- FRAMING --------------------
    ("framing", "Extreme wide shot", "extreme wide shot", 55, ["EWS"]),
    ("framing", "Wide establishing shot", "wide establishing shot", 60, ["establishing wide"]),
    ("framing", "Wide shot", "wide shot", 55, ["WS"]),
    ("framing", "Full-body shot", "full-body shot", 55, ["full-body"]),
    ("framing", "Three-quarter shot", "three-quarter shot", 55, ["3/4 shot"]),
    ("framing", "Cowboy shot", "cowboy shot", 55, ["mid-thigh shot"]),
    ("framing", "Medium shot", "medium shot", 55, ["MS"]),
    ("framing", "Medium close-up", "medium close-up", 55, ["MCU"]),
    ("framing", "Close-up", "close-up", 60, ["CU"]),
    ("framing", "Extreme close-up", "extreme close-up", 70, ["ECU"]),
    ("framing", "Macro close-up", "macro close-up", 70, ["macro shot"]),
    ("framing", "Detail insert shot", "detail insert shot", 60, ["detail shot"]),
    ("framing", "Two-shot", "two-shot", 55, ["two characters"]),
    ("framing", "Group shot", "group shot", 55, ["group framing"]),
    ("framing", "Over-the-shoulder shot", "over-the-shoulder shot", 55, ["OTS"]),
    ("framing", "Point-of-view shot", "point-of-view shot", 60, ["POV shot"]),
    # -------------------- CAMERA ANGLE --------------------
    ("angle", "Eye level", "eye level", 55, ["straight-on"]),
    ("angle", "Low angle", "low angle", 55, ["looking up at subject"]),
    ("angle", "Extreme low angle", "extreme low angle", 65, ["hero angle"]),
    ("angle", "Worm's-eye view", "worm's-eye view", 65, ["worm's eye"]),
    ("angle", "High angle", "high angle", 55, ["looking down at subject"]),
    ("angle", "Extreme high angle", "extreme high angle", 60, ["top-down high"]),
    ("angle", "Bird's-eye view", "bird's-eye view", 60, ["bird's eye"]),
    ("angle", "Top-down", "top-down", 55, ["directly overhead"]),
    ("angle", "Overhead", "overhead", 55, ["overhead"]),
    ("angle", "Dutch angle", "Dutch angle", 55, ["tilted angle"]),
    ("angle", "Canted angle", "canted angle", 55, ["canted"]),
    ("angle", "Ground-level camera", "ground-level camera", 55, ["ground level"]),
    ("angle", "Hip-level camera", "hip-level camera", 55, ["hip level"]),
    ("angle", "Shoulder-level camera", "shoulder-level camera", 55, ["shoulder level"]),
    ("angle", "Behind-subject angle", "behind-subject angle", 55, ["behind subject"]),
    ("angle", "Profile angle", "profile angle", 55, ["side profile"]),
    ("angle", "Three-quarter facial angle", "three-quarter facial angle", 55, ["3/4 facial"]),
    ("angle", "Straight-on frontal angle", "straight-on frontal angle", 55, ["head-on"]),
    # -------------------- CAMERA POSITION --------------------
    ("perspective", "Face close to the lens", "face close to the lens", 60, ["intimate close"]),
    ("perspective", "Subject far from the lens", "subject far from the lens", 55, ["distant lens"]),
    ("perspective", "Forced perspective", "forced perspective", 60, ["perspective trick"]),
    ("perspective", "Wide-angle forced perspective", "wide-angle forced perspective", 65, ["wide trick"]),
    ("perspective", "Compressed telephoto perspective", "compressed telephoto perspective", 60, ["telephoto compression"]),
    ("perspective", "Deep spatial perspective", "deep spatial perspective", 55, ["deep perspective"]),
    ("perspective", "Flat compressed perspective", "flat compressed perspective", 55, ["flat perspective"]),
    ("perspective", "Foreground-dominant composition", "foreground-dominant composition", 55, ["foreground bias"]),
    ("perspective", "Background-dominant composition", "background-dominant composition", 55, ["background bias"]),
    ("perspective", "Camera behind foreground obstruction", "camera behind foreground obstruction", 55, ["obstructed lens"]),
    ("perspective", "Camera inside the action", "camera inside the action", 60, ["immersive camera"]),
    ("perspective", "Intimate camera distance", "intimate camera distance", 60, ["close camera"]),
    ("perspective", "Observational camera distance", "observational camera distance", 55, ["distant camera"]),
    ("perspective", "Distant environmental framing", "distant environmental framing", 55, ["landscape distance"]),
    ("perspective", "Macro perspective", "macro perspective", 60, ["macro lens"]),
    ("perspective", "Fisheye perspective", "fisheye perspective", 60, ["fisheye"]),
    ("perspective", "Tilt-shift perspective", "tilt-shift perspective", 60, ["tilt-shift"]),
    # -------------------- BIPOLAR / DISTANCE --------------------
    # -------------------- LENS / FOCAL LENGTH --------------------
    ("lens", "8mm fisheye", "8mm fisheye", 55, ["fisheye"]),
    ("lens", "14mm ultra-wide", "14mm ultra-wide", 55, ["ultra-wide"]),
    ("lens", "18mm ultra-wide", "18mm ultra-wide", 55, ["ultra-wide"]),
    ("lens", "21mm wide", "21mm wide", 55, ["wide"]),
    ("lens", "24mm wide", "24mm wide", 55, ["wide-angle"]),
    ("lens", "28mm wide", "28mm wide", 55, ["wide"]),
    ("lens", "35mm documentary", "35mm documentary", 55, ["thirty-five"]),
    ("lens", "40mm natural wide", "40mm natural wide", 55, ["forty"]),
    ("lens", "50mm normal", "50mm normal", 55, ["nifty fifty"]),
    ("lens", "58mm vintage normal", "58mm vintage normal", 55, ["vintage 58"]),
    ("lens", "65mm portrait-normal", "65mm portrait-normal", 55, ["sixty-five"]),
    ("lens", "75mm portrait", "75mm portrait", 55, ["seventy-five"]),
    ("lens", "85mm portrait", "85mm portrait", 55, ["eighty-five"]),
    ("lens", "100mm portrait", "100mm portrait", 55, ["hundred"]),
    ("lens", "105mm macro", "105mm macro", 55, ["macro 105"]),
    ("lens", "135mm telephoto portrait", "135mm telephoto portrait", 55, ["telephoto"]),
    ("lens", "200mm telephoto", "200mm telephoto", 55, ["long lens"]),
    ("lens", "300mm long telephoto", "300mm long telephoto", 55, ["three hundred"]),
    ("lens", "600mm extreme telephoto", "600mm extreme telephoto", 60, ["super telephoto"]),
    # -------------------- APERTURE / DOF --------------------
    ("aperture", "f/1.0", "f/1.0", 55, ["f1.0"]),
    ("aperture", "f/1.2", "f/1.2", 55, ["f1.2"]),
    ("aperture", "f/1.4", "f/1.4", 55, ["f1.4"]),
    ("aperture", "f/1.8", "f/1.8", 55, ["f1.8"]),
    ("aperture", "f/2", "f/2", 55, ["f2"]),
    ("aperture", "f/2.8", "f/2.8", 55, ["f2.8"]),
    ("aperture", "f/4", "f/4", 55, ["f4"]),
    ("aperture", "f/5.6", "f/5.6", 55, ["f5.6"]),
    ("aperture", "f/8", "f/8", 55, ["f8"]),
    ("aperture", "f/11", "f/11", 55, ["f11"]),
    ("aperture", "f/16", "f/16", 55, ["f16"]),
    ("aperture", "Extremely shallow depth of field", "extremely shallow depth of field", 70, ["razor-thin DoF"]),
    ("aperture", "Shallow depth of field", "shallow depth of field", 65, ["shallow DoF"]),
    ("aperture", "Moderate depth of field", "moderate depth of field", 55, ["mid DoF"]),
    ("aperture", "Deep focus", "deep focus", 60, ["deep DoF"]),
    ("aperture", "Everything in sharp focus", "everything in sharp focus", 60, ["all sharp"]),
    ("aperture", "Foreground bokeh", "foreground bokeh", 55, ["front bokeh"]),
    ("aperture", "Background bokeh", "background bokeh", 55, ["background bokeh"]),
    ("aperture", "Creamy bokeh", "creamy bokeh", 55, ["smooth bokeh"]),
    ("aperture", "Swirled bokeh", "swirled bokeh", 55, ["swirly bokeh"]),
    ("aperture", "Busy geometric bokeh", "busy geometric bokeh", 55, ["bokeh pattern"]),
    ("aperture", "Rack-focus appearance", "rack-focus appearance", 60, ["focus pull"]),
    # -------------------- CAMERA BODY / FORMAT --------------------
    ("camera_body", "ARRI Alexa 35", "ARRI Alexa 35", 35, ["Alexa 35"]),
    ("camera_body", "ARRI Alexa Mini LF", "ARRI Alexa Mini LF", 35, ["Alexa Mini LF"]),
    ("camera_body", "Sony Venice 2", "Sony Venice 2", 35, ["Venice 2"]),
    ("camera_body", "RED V-Raptor XL", "RED V-Raptor XL", 35, ["V-Raptor"]),
    ("camera_body", "Blackmagic URSA Cine 12K", "Blackmagic URSA Cine 12K", 35, ["URSA Cine"]),
    ("camera_body", "Sony FX3", "Sony FX3", 35, ["FX3"]),
    ("camera_body", "Sony Alpha 1", "Sony Alpha 1", 35, ["Sony A1"]),
    ("camera_body", "Canon EOS R5", "Canon EOS R5", 35, ["R5"]),
    ("camera_body", "Canon EOS R3", "Canon EOS R3", 35, ["R3"]),
    ("camera_body", "Nikon Z8", "Nikon Z8", 35, ["Z8"]),
    ("camera_body", "Nikon Z9", "Nikon Z9", 35, ["Z9"]),
    ("camera_body", "Fujifilm GFX100 II", "Fujifilm GFX100 II", 35, ["GFX100 II"]),
    ("camera_body", "Fujifilm X-T5", "Fujifilm X-T5", 35, ["X-T5"]),
    ("camera_body", "Hasselblad X2D 100C", "Hasselblad X2D 100C", 35, ["X2D"]),
    ("camera_body", "Leica M11", "Leica M11", 35, ["M11"]),
    ("camera_body", "Panasonic Lumix S5IIX", "Panasonic Lumix S5IIX", 35, ["S5IIX"]),
    ("camera_body", "Phase One XF", "Phase One XF", 35, ["Phase One"]),
    ("camera_body", "IMAX 65mm camera", "IMAX 65mm camera", 35, ["IMAX"]),
    ("camera_body", "Panavision Panaflex Millennium XL2", "Panavision Panaflex Millennium XL2", 35, ["Panavision"]),
    ("camera_body", "ARRIFLEX 435", "ARRIFLEX 435", 35, ["Arri 435"]),
    ("camera_body", "ARRIFLEX 16SR", "ARRIFLEX 16SR", 35, ["Arri 16SR"]),
    ("camera_body", "Bolex H16", "Bolex H16", 35, ["Bolex"]),
    ("camera_body", "Super 8 camera", "Super 8 camera", 35, ["Super 8"]),
    ("camera_body", "Disposable 35mm camera", "disposable 35mm camera", 35, ["disposable"]),
    ("camera_body", "Instant-film camera", "instant-film camera", 35, ["Polaroid style"]),
    ("camera_body", "Large-format view camera", "large-format view camera", 35, ["view camera"]),
    ("camera_body", "Medium-format film camera", "medium-format film camera", 35, ["medium format"]),
    # -------------------- LENS FAMILIES --------------------
    ("lens_family", "ARRI Signature Prime", "ARRI Signature Prime", 35, ["Signature Prime"]),
    ("lens_family", "Zeiss Master Prime", "Zeiss Master Prime", 35, ["Master Prime"]),
    ("lens_family", "Zeiss Supreme Prime", "Zeiss Supreme Prime", 35, ["Supreme Prime"]),
    ("lens_family", "Cooke S4", "Cooke S4", 35, ["Cooke S4"]),
    ("lens_family", "Cooke Panchro", "Cooke Panchro", 35, ["Panchro"]),
    ("lens_family", "Leica Summilux-C", "Leica Summilux-C", 35, ["Summilux-C"]),
    ("lens_family", "Panavision Primo", "Panavision Primo", 35, ["Primo"]),
    ("lens_family", "Panavision C Series anamorphic", "Panavision C Series anamorphic", 35, ["Panavision C"]),
    ("lens_family", "Hawk V-Lite anamorphic", "Hawk V-Lite anamorphic", 35, ["Hawk V-Lite"]),
    ("lens_family", "Atlas Orion anamorphic", "Atlas Orion anamorphic", 35, ["Atlas Orion"]),
    ("lens_family", "Canon K35", "Canon K35", 35, ["K35"]),
    ("lens_family", "Canon FD vintage lens", "Canon FD vintage lens", 35, ["FD vintage"]),
    ("lens_family", "Nikon AI-S vintage lens", "Nikon AI-S vintage lens", 35, ["AI-S"]),
    ("lens_family", "Helios 44-2", "Helios 44-2", 35, ["Helios"]),
    ("lens_family", "Petzval portrait lens", "Petzval portrait lens", 35, ["Petzval"]),
    ("lens_family", "Probe macro lens", "probe macro lens", 35, ["Probe"]),
    ("lens_family", "Vintage uncoated lens", "vintage uncoated lens", 35, ["uncoated"]),
    ("lens_family", "Modern clinical cinema lens", "modern clinical cinema lens", 35, ["clinical"]),
    ("lens_family", "Soft-focus portrait lens", "soft-focus portrait lens", 35, ["soft-focus"]),
    ("lens_family", "Catadioptric mirror lens", "catadioptric mirror lens", 35, ["mirror lens"]),
    # -------------------- COMPOSITION --------------------
    ("composition", "Centered composition", "centered composition", 55, ["centered"]),
    ("composition", "Symmetrical composition", "symmetrical composition", 55, ["symmetrical"]),
    ("composition", "Asymmetrical composition", "asymmetrical composition", 55, ["asymmetrical"]),
    ("composition", "Rule of thirds", "rule of thirds", 60, ["thirds"]),
    ("composition", "Golden-ratio composition", "golden-ratio composition", 55, ["golden ratio"]),
    ("composition", "Leading lines", "leading lines", 60, ["leading lines"]),
    ("composition", "Diagonal composition", "diagonal composition", 55, ["diagonal"]),
    ("composition", "Triangular composition", "triangular composition", 55, ["triangular"]),
    ("composition", "Radial composition", "radial composition", 55, ["radial"]),
    ("composition", "Frame within a frame", "frame within a frame", 60, ["re-framing"]),
    ("composition", "Layered foreground, midground, and background", "layered foreground, midground, and background", 55, ["layered"]),
    ("composition", "Strong negative space", "strong negative space", 55, ["negative space"]),
    ("composition", "Foreground occlusion", "foreground occlusion", 55, ["foreground occlusion"]),
    ("composition", "Low horizon", "low horizon", 55, ["low horizon"]),
    ("composition", "High horizon", "high horizon", 55, ["high horizon"]),
    ("composition", "Subject on left", "subject on left", 50, ["left-framed"]),
    ("composition", "Subject on right", "subject on right", 50, ["right-framed"]),
    ("composition", "Dynamic left-heavy composition", "dynamic left-heavy composition", 55, ["left-heavy"]),
    ("composition", "Dynamic right-heavy composition", "dynamic right-heavy composition", 55, ["right-heavy"]),
    ("composition", "Balanced composition", "balanced composition", 55, ["balanced"]),
    ("composition", "Unbalanced tense composition", "unbalanced tense composition", 55, ["unbalanced"]),
    ("composition", "Flat graphic composition", "flat graphic composition", 55, ["flat graphic"]),
    ("composition", "Dense edge-to-edge composition", "dense edge-to-edge composition", 55, ["edge-to-edge"]),
    ("composition", "Split composition", "split composition", 55, ["split"]),
    ("composition", "Mirrored composition", "mirrored composition", 55, ["mirrored"]),
    ("composition", "Repeating-pattern composition", "repeating-pattern composition", 55, ["repeating pattern"]),
    # -------------------- LIGHTING SETUP --------------------
    ("lighting_setup", "Soft diffused lighting", "soft diffused lighting", 55, ["soft light"]),
    ("lighting_setup", "Hard directional lighting", "hard directional lighting", 55, ["hard light"]),
    ("lighting_setup", "Three-point lighting", "three-point lighting", 55, ["3-point"]),
    ("lighting_setup", "High-key lighting", "high-key lighting", 55, ["high key"]),
    ("lighting_setup", "Low-key lighting", "low-key lighting", 55, ["low key"]),
    ("lighting_setup", "Chiaroscuro", "chiaroscuro", 60, ["light/shadow contrast"]),
    ("lighting_setup", "Rembrandt lighting", "Rembrandt lighting", 55, ["Rembrandt"]),
    ("lighting_setup", "Loop lighting", "loop lighting", 55, ["loop"]),
    ("lighting_setup", "Butterfly lighting", "butterfly lighting", 55, ["butterfly"]),
    ("lighting_setup", "Clamshell lighting", "clamshell lighting", 55, ["clamshell"]),
    ("lighting_setup", "Split lighting", "split lighting", 55, ["split"]),
    ("lighting_setup", "Broad lighting", "broad lighting", 55, ["broad"]),
    ("lighting_setup", "Short lighting", "short lighting", 55, ["short"]),
    ("lighting_setup", "Beauty-dish lighting", "beauty-dish lighting", 55, ["beauty dish"]),
    ("lighting_setup", "Large softbox lighting", "large softbox lighting", 55, ["softbox"]),
    ("lighting_setup", "Window lighting", "window lighting", 55, ["window light"]),
    ("lighting_setup", "Direct frontal flash", "direct frontal flash", 55, ["frontal flash"]),
    ("lighting_setup", "On-camera flash", "on-camera flash", 55, ["speedlight"]),
    ("lighting_setup", "Ring-light illumination", "ring-light illumination", 55, ["ring light"]),
    ("lighting_setup", "Overcast natural lighting", "overcast natural lighting", 55, ["overcast"]),
    ("lighting_setup", "Golden-hour lighting", "golden-hour lighting", 60, ["golden hour"]),
    ("lighting_setup", "Blue-hour lighting", "blue-hour lighting", 60, ["blue hour"]),
    ("lighting_setup", "Midday sunlight", "midday sunlight", 55, ["midday"]),
    ("lighting_setup", "Open-shade lighting", "open-shade lighting", 55, ["open shade"]),
    ("lighting_setup", "Candlelight", "candlelight", 55, ["candle"]),
    ("lighting_setup", "Firelight", "firelight", 55, ["fire"]),
    ("lighting_setup", "Moonlight", "moonlight", 55, ["moon"]),
    ("lighting_setup", "Neon lighting", "neon lighting", 55, ["neon"]),
    ("lighting_setup", "Fluorescent lighting", "fluorescent lighting", 55, ["fluorescent"]),
    ("lighting_setup", "Tungsten lighting", "tungsten lighting", 55, ["tungsten"]),
    ("lighting_setup", "Sodium-vapour lighting", "sodium-vapour lighting", 55, ["sodium"]),
    ("lighting_setup", "Mixed-colour practical lighting", "mixed-colour practical lighting", 55, ["mixed practical"]),
    ("lighting_setup", "Stage spotlight", "stage spotlight", 55, ["spotlight"]),
    ("lighting_setup", "Theatrical lighting", "theatrical lighting", 55, ["theatrical"]),
    ("lighting_setup", "Underwater caustic lighting", "underwater caustic lighting", 60, ["underwater"]),
    # -------------------- LIGHTING DIRECTION --------------------
    ("lighting_direction", "Front lighting", "front lighting", 55, ["front lit"]),
    ("lighting_direction", "Three-quarter front lighting", "three-quarter front lighting", 55, ["3/4 front"]),
    ("lighting_direction", "Side lighting", "side lighting", 55, ["side-lit"]),
    ("lighting_direction", "Cross lighting", "cross lighting", 55, ["cross-lit"]),
    ("lighting_direction", "Top lighting", "top lighting", 55, ["top lit"]),
    ("lighting_direction", "Underlighting", "underlighting", 55, ["under-lit"]),
    ("lighting_direction", "Backlighting", "backlighting", 55, ["back lit"]),
    ("lighting_direction", "Strong backlighting", "strong backlighting", 65, ["strong backlit"]),
    ("lighting_direction", "Rim lighting", "rim lighting", 60, ["rim lit"]),
    ("lighting_direction", "Edge lighting", "edge lighting", 55, ["edge lit"]),
    ("lighting_direction", "Kicker light", "kicker light", 55, ["kicker"]),
    ("lighting_direction", "Hair light", "hair light", 55, ["hair light"]),
    ("lighting_direction", "Silhouette lighting", "silhouette lighting", 60, ["silhouette"]),
    ("lighting_direction", "Light from camera left", "light from camera left", 55, ["left lit"]),
    ("lighting_direction", "Light from camera right", "light from camera right", 55, ["right lit"]),
    ("lighting_direction", "Light from above and behind", "light from above and behind", 55, ["above-behind"]),
    ("lighting_direction", "Light from below", "light from below", 55, ["below lit"]),
    ("lighting_direction", "Light through a window", "light through a window", 55, ["window light"]),
    ("lighting_direction", "Dappled light through leaves", "dappled light through leaves", 60, ["leaf dappled"]),
    ("lighting_direction", "Light through blinds", "light through blinds", 55, ["blind slats"]),
    # -------------------- LIGHTING EFFECT --------------------
    ("lighting_effect", "Cinematic light halation", "cinematic light halation", 60, ["halation"]),
    ("lighting_effect", "Subtle halation", "subtle halation", 55, ["gentle halation"]),
    ("lighting_effect", "Pronounced halation", "pronounced halation", 60, ["heavy halation"]),
    ("lighting_effect", "Radiant edge illumination", "radiant edge illumination", 55, ["radiant edges"]),
    ("lighting_effect", "Soft bloom", "soft bloom", 55, ["bloom"]),
    ("lighting_effect", "Highlight bloom", "highlight bloom", 55, ["highlight bloom"]),
    ("lighting_effect", "Anamorphic lens flare", "anamorphic lens flare", 60, ["anamorphic flare"]),
    ("lighting_effect", "Horizontal anamorphic streak", "horizontal anamorphic streak", 60, ["streak flare"]),
    ("lighting_effect", "Starburst flare", "starburst flare", 55, ["starburst"]),
    ("lighting_effect", "Volumetric light", "volumetric light", 55, ["volumetric"]),
    ("lighting_effect", "God rays", "god rays", 60, ["crepuscular rays"]),
    ("lighting_effect", "Atmospheric light shafts", "atmospheric light shafts", 55, ["light shafts"]),
    ("lighting_effect", "Glowing practical lights", "glowing practical lights", 55, ["glowing practical"]),
    ("lighting_effect", "Specular highlights", "specular highlights", 55, ["spec hits"]),
    ("lighting_effect", "Wet reflective highlights", "wet reflective highlights", 55, ["wet specular"]),
    ("lighting_effect", "Dappled shadows", "dappled shadows", 55, ["dappled"]),
    ("lighting_effect", "Hard graphic shadows", "hard graphic shadows", 55, ["hard shadows"]),
    ("lighting_effect", "Soft feathered shadows", "soft feathered shadows", 55, ["soft shadows"]),
    ("lighting_effect", "Coloured shadows", "coloured shadows", 55, ["colour shadows"]),
    ("lighting_effect", "Light leaks", "light leaks", 55, ["leaks"]),
    ("lighting_effect", "Chromatic flare", "chromatic flare", 55, ["chromatic"]),
    ("lighting_effect", "Reflected bounce light", "reflected bounce light", 55, ["bounce"]),
    ("lighting_effect", "Caustic reflections", "caustic reflections", 55, ["caustics"]),
    ("lighting_effect", "Flickering firelight", "flickering firelight", 55, ["flickering fire"]),
    ("lighting_effect", "Pulsing neon", "pulsing neon", 55, ["pulsing"]),
    ("lighting_effect", "Overexposed highlights", "overexposed highlights", 55, ["blown highlights"]),
    ("lighting_effect", "Underexposed shadows", "underexposed shadows", 55, ["crushed shadows"]),
    # -------------------- SUBJECT MOVEMENT --------------------
    ("subject_movement", "Still subject", "still subject", 55, ["stationary"]),
    ("subject_movement", "Subtle natural movement", "subtle natural movement", 55, ["natural movement"]),
    ("subject_movement", "Walking", "walking", 55, ["strolling"]),
    ("subject_movement", "Running", "running", 60, ["sprinting"]),
    ("subject_movement", "Sprinting", "sprinting", 60, ["full sprint"]),
    ("subject_movement", "Jumping", "jumping", 60, ["leaping"]),
    ("subject_movement", "Falling", "falling", 65, ["tumbling"]),
    ("subject_movement", "Spinning", "spinning", 55, ["rotating"]),
    ("subject_movement", "Turning", "turning", 55, ["pivoting"]),
    ("subject_movement", "Reaching", "reaching", 55, ["extending"]),
    ("subject_movement", "Lunging", "lunging", 60, ["lunging forward"]),
    ("subject_movement", "Dancing", "dancing", 55, ["dancer"]),
    ("subject_movement", "Hair blowing", "hair blowing", 55, ["windblown hair"]),
    ("subject_movement", "Clothing billowing", "clothing billowing", 55, ["billowing"]),
    ("subject_movement", "Fabric fluttering", "fabric fluttering", 55, ["flutter"]),
    ("subject_movement", "Frozen action", "frozen action", 60, ["frozen mid-action"]),
    ("subject_movement", "Controlled motion blur", "controlled motion blur", 60, ["controlled blur"]),
    ("subject_movement", "Strong motion blur", "strong motion blur", 65, ["heavy motion blur"]),
    ("subject_movement", "Directional motion blur", "directional motion blur", 60, ["directional blur"]),
    ("subject_movement", "Long-exposure movement trails", "long-exposure movement trails", 60, ["exposure trails"]),
    # -------------------- CAMERA MOVEMENT --------------------
    ("camera_movement", "Locked-off camera", "locked-off camera", 55, ["tripod still"]),
    ("camera_movement", "Handheld camera", "handheld camera", 55, ["handheld"]),
    ("camera_movement", "Subtle handheld drift", "subtle handheld drift", 55, ["drift"]),
    ("camera_movement", "Pan left", "pan left", 55, ["left pan"]),
    ("camera_movement", "Pan right", "pan right", 55, ["right pan"]),
    ("camera_movement", "Tilt up", "tilt up", 55, ["up tilt"]),
    ("camera_movement", "Tilt down", "tilt down", 55, ["down tilt"]),
    ("camera_movement", "Dolly in", "dolly in", 55, ["push in"]),
    ("camera_movement", "Dolly out", "dolly out", 55, ["pull out"]),
    ("camera_movement", "Truck left", "truck left", 55, ["sideways left"]),
    ("camera_movement", "Truck right", "truck right", 55, ["sideways right"]),
    ("camera_movement", "Pedestal up", "pedestal up", 55, ["lift up"]),
    ("camera_movement", "Pedestal down", "pedestal down", 55, ["drop down"]),
    ("camera_movement", "Crane movement", "crane movement", 55, ["crane"]),
    ("camera_movement", "Jib movement", "jib movement", 55, ["jib"]),
    ("camera_movement", "Orbit around subject", "orbit around subject", 55, ["orbital"]),
    ("camera_movement", "Arc shot", "arc shot", 55, ["arc"]),
    ("camera_movement", "Push-in", "push-in", 55, ["push in"]),
    ("camera_movement", "Pull-back", "pull-back", 55, ["pull back"]),
    ("camera_movement", "Whip pan", "whip pan", 65, ["whip"]),
    ("camera_movement", "Snap zoom", "snap zoom", 65, ["snap zoom"]),
    ("camera_movement", "Slow zoom", "slow zoom", 55, ["slow zoom"]),
    ("camera_movement", "Crash zoom", "crash zoom", 65, ["crash zoom"]),
    ("camera_movement", "Rack focus", "rack focus", 55, ["focus pull"]),
    ("camera_movement", "Drone flyover", "drone flyover", 55, ["drone"]),
    ("camera_movement", "POV movement", "POV movement", 55, ["first-person"]),
    ("camera_movement", "Body-mounted camera", "body-mounted camera", 55, ["body cam"]),
    ("camera_movement", "Rapid forward camera movement", "rapid forward camera movement", 65, ["rush forward"]),
    # -------------------- ENVIRONMENTAL MOVEMENT --------------------
    ("environment_movement", "Gentle breeze", "gentle breeze", 55, ["light breeze"]),
    ("environment_movement", "Strong wind", "strong wind", 60, ["gale"]),
    ("environment_movement", "Hair moving in wind", "hair moving in wind", 55, ["windblown"]),
    ("environment_movement", "Clothing moving in wind", "clothing moving in wind", 55, ["windblown clothing"]),
    ("environment_movement", "Fabric fluttering", "fabric fluttering", 55, ["flutter"]),
    ("environment_movement", "Leaves moving through air", "leaves moving through air", 55, ["flying leaves"]),
    ("environment_movement", "Dust moving through air", "dust moving through air", 55, ["dust motes"]),
    ("environment_movement", "Fog swirling", "fog swirling", 55, ["swirling fog"]),
    ("environment_movement", "Smoke drifting", "smoke drifting", 55, ["drift smoke"]),
    ("environment_movement", "Rain driven sideways", "rain driven sideways", 55, ["sideways rain"]),
    ("environment_movement", "Snow blowing", "snow blowing", 55, ["blowing snow"]),
    ("environment_movement", "Embers floating", "embers floating", 55, ["floating embers"]),
    ("environment_movement", "Debris suspended in air", "debris suspended in air", 55, ["hovering debris"]),
    ("environment_movement", "Water splashing", "water splashing", 55, ["splashing"]),
    ("environment_movement", "Waves crashing", "waves crashing", 55, ["crashing waves"]),
    # -------------------- WEATHER / ATMOSPHERE --------------------
    ("atmosphere", "Clear air", "clear air", 55, ["clear"]),
    ("atmosphere", "Light haze", "light haze", 55, ["hazy"]),
    ("atmosphere", "Dense haze", "dense haze", 55, ["heavy haze"]),
    ("atmosphere", "Mist", "mist", 55, ["misty"]),
    ("atmosphere", "Fog", "fog", 55, ["foggy"]),
    ("atmosphere", "Dense cinematic fog", "dense cinematic fog", 60, ["cinematic fog"]),
    ("atmosphere", "Ground fog", "ground fog", 55, ["low fog"]),
    ("atmosphere", "Smoke", "smoke", 55, ["smoky"]),
    ("atmosphere", "Dust", "dust", 55, ["dusty"]),
    ("atmosphere", "Floating dust particles", "floating dust particles", 55, ["dust particles"]),
    ("atmosphere", "Pollen", "pollen", 50, ["pollen"]),
    ("atmosphere", "Embers", "embers", 55, ["embers"]),
    ("atmosphere", "Ash", "ash", 55, ["ashfall"]),
    ("atmosphere", "Light rain", "light rain", 55, ["drizzle"]),
    ("atmosphere", "Heavy rain", "heavy rain", 60, ["downpour"]),
    ("atmosphere", "Driving rain", "driving rain", 60, ["driving rain"]),
    ("atmosphere", "Storm", "storm", 60, ["stormy"]),
    ("atmosphere", "Thunderstorm", "thunderstorm", 60, ["thunder"]),
    ("atmosphere", "Snowfall", "snowfall", 55, ["snow"]),
    ("atmosphere", "Heavy snowfall", "heavy snowfall", 60, ["heavy snow"]),
    ("atmosphere", "Blizzard", "blizzard", 65, ["blizzard"]),
    ("atmosphere", "Hail", "hail", 60, ["hailing"]),
    ("atmosphere", "Wind", "wind", 55, ["wind"]),
    ("atmosphere", "Strong wind", "strong wind", 60, ["strong wind"]),
    ("atmosphere", "Heat shimmer", "heat shimmer", 55, ["shimmer"]),
    ("atmosphere", "Humid atmosphere", "humid atmosphere", 55, ["humid"]),
    ("atmosphere", "Dry desert air", "dry desert air", 55, ["desert"]),
    ("atmosphere", "Underwater atmosphere", "underwater atmosphere", 60, ["underwater"]),
    ("atmosphere", "Cloud-filled sky", "cloud-filled sky", 55, ["cloudy"]),
    ("atmosphere", "Billowing storm clouds", "billowing storm clouds", 60, ["storm clouds"]),
    ("atmosphere", "Sunbeams through clouds", "sunbeams through clouds", 60, ["god rays"]),
    # -------------------- STYLE / MEDIUM --------------------
    ("style", "Natural photographic realism", "natural photographic realism", 60, ["photo realism"]),
    ("style", "Cinematic film still", "cinematic film still", 65, ["film still"]),
    ("style", "Fashion editorial", "fashion editorial", 60, ["editorial"]),
    ("style", "Documentary photography", "documentary photography", 55, ["documentary"]),
    ("style", "Street photography", "street photography", 55, ["street"]),
    ("style", "Direct-flash snapshot", "direct-flash snapshot", 55, ["direct flash"]),
    ("style", "Commercial product photography", "commercial product photography", 55, ["product"]),
    ("style", "Architectural photography", "architectural photography", 55, ["architectural"]),
    ("style", "Sports photography", "sports photography", 55, ["sports"]),
    ("style", "Macro photography", "macro photography", 55, ["macro"]),
    ("style", "Analog 35mm photography", "analog 35mm photography", 55, ["35mm film"]),
    ("style", "Medium-format photography", "medium-format photography", 55, ["medium format"]),
    ("style", "Large-format photography", "large-format photography", 55, ["large format"]),
    ("style", "Instant-film photography", "instant-film photography", 55, ["instant film"]),
    ("style", "Watercolour painting", "watercolour painting", 55, ["watercolour"]),
    ("style", "Oil painting", "oil painting", 55, ["oil"]),
    ("style", "Gouache", "gouache", 55, ["gouache"]),
    ("style", "Acrylic painting", "acrylic painting", 55, ["acrylic"]),
    ("style", "Ink drawing", "ink drawing", 55, ["ink"]),
    ("style", "Pen-and-ink illustration", "pen-and-ink illustration", 55, ["pen and ink"]),
    ("style", "Charcoal drawing", "charcoal drawing", 55, ["charcoal"]),
    ("style", "Graphite drawing", "graphite drawing", 55, ["graphite"]),
    ("style", "Pastel drawing", "pastel drawing", 55, ["pastel"]),
    ("style", "Cel animation", "cel animation", 55, ["cel"]),
    ("style", "Anime illustration", "anime illustration", 55, ["anime"]),
    ("style", "Graphic-novel illustration", "graphic-novel illustration", 55, ["graphic novel"]),
    ("style", "Comic-book art", "comic-book art", 55, ["comic"]),
    ("style", "Editorial illustration", "editorial illustration", 55, ["editorial illustration"]),
    ("style", "Concept art", "concept art", 55, ["concept"]),
    ("style", "Matte painting", "matte painting", 55, ["matte"]),
    ("style", "Photorealistic 3D render", "photorealistic 3D render", 55, ["3D render"]),
    ("style", "Clay render", "clay render", 55, ["clay"]),
    ("style", "Papercraft", "papercraft", 55, ["paper"]),
    ("style", "Paper collage", "paper collage", 55, ["paper collage"]),
    ("style", "Analog collage", "analog collage", 55, ["analog collage"]),
    ("style", "Risograph print", "Risograph print", 55, ["risograph"]),
    ("style", "Screen print", "screen print", 55, ["screen print"]),
    ("style", "Linocut", "linocut", 55, ["linocut"]),
    ("style", "Woodcut", "woodcut", 55, ["woodcut"]),
    ("style", "Stained glass", "stained glass", 55, ["stained glass"]),
    ("style", "Low-poly render", "low-poly render", 55, ["low poly"]),
    ("style", "Pixel art", "pixel art", 55, ["pixel"]),
    # -------------------- FILM / COLOUR --------------------
    ("film_color", "Kodak Portra 160", "Kodak Portra 160", 55, ["Portra 160"]),
    ("film_color", "Kodak Portra 400", "Kodak Portra 400", 55, ["Portra 400"]),
    ("film_color", "Kodak Portra 800", "Kodak Portra 800", 55, ["Portra 800"]),
    ("film_color", "Kodak Gold 200", "Kodak Gold 200", 55, ["Gold 200"]),
    ("film_color", "Kodak Ektar 100", "Kodak Ektar 100", 55, ["Ektar"]),
    ("film_color", "Kodak Ektachrome", "Kodak Ektachrome", 55, ["Ektachrome"]),
    ("film_color", "Kodak Vision3 250D", "Kodak Vision3 250D", 55, ["Vision3 250D"]),
    ("film_color", "Kodak Vision3 500T", "Kodak Vision3 500T", 55, ["Vision3 500T"]),
    ("film_color", "Kodachrome character", "Kodachrome character", 55, ["Kodachrome"]),
    ("film_color", "Fujifilm Pro 400H", "Fujifilm Pro 400H", 55, ["Pro 400H"]),
    ("film_color", "Fujifilm Velvia", "Fujifilm Velvia", 55, ["Velvia"]),
    ("film_color", "Fujifilm Classic Chrome", "Fujifilm Classic Chrome", 55, ["Classic Chrome"]),
    ("film_color", "Ilford HP5", "Ilford HP5", 55, ["HP5"]),
    ("film_color", "Ilford Delta 100", "Ilford Delta 100", 55, ["Delta 100"]),
    ("film_color", "CineStill 800T", "CineStill 800T", 60, ["CineStill"]),
    ("film_color", "Agfa Vista character", "Agfa Vista character", 55, ["Agfa Vista"]),
    ("film_color", "Bleach bypass", "bleach bypass", 60, ["bleach bypass"]),
    ("film_color", "Cross-processed colour", "cross-processed colour", 55, ["cross-processed"]),
    ("film_color", "Teal-and-amber grade", "teal-and-amber grade", 55, ["teal and amber"]),
    ("film_color", "Muted cinematic palette", "muted cinematic palette", 55, ["muted cinematic"]),
    ("film_color", "Warm golden palette", "warm golden palette", 55, ["warm golden"]),
    ("film_color", "Cool blue palette", "cool blue palette", 55, ["cool blue"]),
    ("film_color", "Pastel palette", "pastel palette", 55, ["pastel"]),
    ("film_color", "Desaturated palette", "desaturated palette", 55, ["desaturated"]),
    ("film_color", "Rich saturated palette", "rich saturated palette", 55, ["rich saturated"]),
    ("film_color", "Monochrome", "monochrome", 55, ["B&W"]),
    ("film_color", "High-contrast black and white", "high-contrast black and white", 55, ["high-contrast B&W"]),
    ("film_color", "Sepia", "sepia", 55, ["sepia"]),
    ("film_color", "Faded vintage colour", "faded vintage colour", 55, ["vintage faded"]),
    ("film_color", "Natural colour reproduction", "natural colour reproduction", 55, ["accurate colour"]),
    # -------------------- TEXTURE --------------------
    ("texture", "Fine film grain", "fine film grain", 55, ["fine grain"]),
    ("texture", "Heavy film grain", "heavy film grain", 55, ["heavy grain"]),
    ("texture", "Digital sensor noise", "digital sensor noise", 55, ["sensor noise"]),
    ("texture", "Smooth clean digital texture", "smooth clean digital texture", 55, ["clean digital"]),
    ("texture", "Paper grain", "paper grain", 55, ["paper grain"]),
    ("texture", "Canvas texture", "canvas texture", 55, ["canvas"]),
    ("texture", "Visible brushstrokes", "visible brushstrokes", 55, ["brushstrokes"]),
    ("texture", "Impasto texture", "impasto texture", 55, ["impasto"]),
    ("texture", "Stippling", "stippling", 55, ["stippled"]),
    ("texture", "Cross-hatching", "cross-hatching", 55, ["hatching"]),
    ("texture", "Halftone dots", "halftone dots", 55, ["halftone"]),
    ("texture", "Screen-print texture", "screen-print texture", 55, ["screen-print"]),
    ("texture", "Weathered surfaces", "weathered surfaces", 55, ["weathered"]),
    ("texture", "Rust", "rust", 55, ["rusted"]),
    ("texture", "Patina", "patina", 55, ["patinated"]),
    ("texture", "Peeling paint", "peeling paint", 55, ["peeling"]),
    ("texture", "Cracked stone", "cracked stone", 55, ["cracked"]),
    ("texture", "Wet surfaces", "wet surfaces", 55, ["wet"]),
    ("texture", "Polished metal", "polished metal", 55, ["polished"]),
    ("texture", "Brushed metal", "brushed metal", 55, ["brushed"]),
    ("texture", "Soft fabric texture", "soft fabric texture", 55, ["fabric"]),
    ("texture", "Intricate embroidery", "intricate embroidery", 55, ["embroidery"]),
    ("texture", "Ornate decoration", "ornate decoration", 55, ["ornate"]),
    # -------------------- DETAIL --------------------
    ("detail", "Minimal detail", "minimal detail", 55, ["minimalist"]),
    ("detail", "Moderate detail", "moderate detail", 55, ["moderate detail"]),
    ("detail", "Intricate detail", "intricate detail", 55, ["intricate"]),
    ("detail", "Dense layered detail", "dense layered detail", 55, ["dense detail"]),
    ("detail", "Highly detailed environment", "highly detailed environment", 55, ["highly detailed"]),
    ("detail", "Uncluttered environment", "uncluttered environment", 55, ["uncluttered"]),
    ("detail", "Complex environmental storytelling", "complex environmental storytelling", 55, ["environmental storytelling"]),
    # -------------------- CUSTOM --------------------
    ("custom", "Custom phrase", "Your custom phrase", 50, ["custom"]),
]


# ---------------------------------------------------------------------------
# Bipolar presets
# ---------------------------------------------------------------------------

BIPOLAR_PRESETS = [
    # category, label, neutral, negative, positive, default_strength, aliases
    ("perspective", "Camera Distance", "subject framed in environment", "distant subject framed deep within the environment", "face close to the lens", 0, ["near", "far"]),
    ("composition", "Symmetry", "balanced composition", "symmetrical composition", "asymmetrical composition", 0, ["mirror"]),
    ("subject_movement", "Subject Stillness", "subtle natural movement", "still subject", "running", 0, ["frozen", "active"]),
    ("lighting_setup", "Lighting Direction Polar", "evenly lit", "front-lit", "backlit", 0, ["key"]),
    ("lighting_setup", "Light Quality", "balanced lighting", "soft diffused lighting", "hard directional lighting", 0, ["hard soft"]),
    ("angle", "Angle Polar", "neutral angle", "low angle", "high angle", 0, ["pitch"]),
    ("detail", "Detail Density", "moderate detail", "minimal detail", "dense layered detail", 0, ["sparse"]),
    ("film_color", "Colour Pop", "natural colour reproduction", "desaturated palette", "rich saturated palette", 0, ["saturation"]),
    ("texture", "Film Grain", "smooth clean digital texture", "fine film grain", "heavy film grain", 0, ["noise"]),
    ("aperture", "Depth of Field", "moderate depth of field", "extremely shallow depth of field", "deep focus", 0, ["DoF"]),
    ("camera_movement", "Camera Stillness", "slow zoom", "locked-off camera", "handheld camera", 0, ["tripod"]),
    ("subject_movement", "Subject Motion", "subtle natural movement", "still subject", "strong motion blur", 0, ["freeze"]),
    ("film_color", "Palette Temperature", "natural colour reproduction", "cool blue palette", "warm golden palette", 0, ["warm cool"]),
    ("lighting_setup", "Contrast", "balanced lighting", "soft diffused lighting", "chiaroscuro", 0, []),
    ("aperture", "Focus Stacking", "moderate depth of field", "extremely shallow depth of field", "deep focus", 0, []),
    ("camera_movement", "Camera Movement Intensity", "subtle handheld drift", "locked-off camera", "whip pan", 0, []),
]


# ---------------------------------------------------------------------------
# Builder
# ---------------------------------------------------------------------------


def _slug(label: str) -> str:
    s = label.lower().replace(" ", "_").replace("-", "_").replace("'", "")
    return "".join(c for c in s if c.isalnum() or c == "_")


def build_preset(
    category: str,
    label: str,
    phrase: str,
    default_strength: int,
    aliases: List[str],
    *,
    verification: str = VERIFICATION_GENERAL,
    source: str = "curated visual vocabulary",
    tags: Optional[List[str]] = None,
) -> Dict[str, Any]:
    return {
        "id": f"{category}.{_slug(label)}",
        "category": category,
        "label": label,
        "phrase": phrase,
        "default_strength": default_strength,
        "control_mode": MODE_SCALAR,
        "aliases": aliases,
        "tags": tags or [category],
        "compatible_profiles": [PROFILE_GENERIC, PROFILE_KREA_TURBO, PROFILE_KREA_RAW],
        "source": source,
        "verification": verification,
        "schema_version": SCHEMA_VERSION,
    }


def build_bipolar(
    category: str,
    label: str,
    neutral_phrase: str,
    negative_phrase: str,
    positive_phrase: str,
    default_strength: int,
    aliases: List[str],
) -> Dict[str, Any]:
    return {
        "id": f"{category}.{_slug(label)}",
        "category": category,
        "label": label,
        "phrase": neutral_phrase,
        "default_strength": default_strength,
        "control_mode": MODE_BIPOLAR,
        "aliases": aliases,
        "tags": [category, "bipolar"],
        "negative_phrase": negative_phrase,
        "neutral_phrase": neutral_phrase,
        "positive_phrase": positive_phrase,
        "safe_weight_min": 0.5,
        "safe_weight_max": 2.5,
        "compatible_profiles": [PROFILE_GENERIC, PROFILE_KREA_TURBO, PROFILE_KREA_RAW],
        "source": "curated visual vocabulary",
        "verification": VERIFICATION_GENERAL,
        "schema_version": SCHEMA_VERSION,
    }


def main() -> None:
    presets: List[Dict[str, Any]] = []

    for entry in PRESETS:
        category, label, phrase, default_strength, aliases = entry
        presets.append(
            build_preset(
                category,
                label,
                phrase,
                default_strength,
                aliases,
                verification=VERIFICATION_GENERAL,
            )
        )

    for entry in BIPOLAR_PRESETS:
        category, label, neutral, negative, positive, default_strength, aliases = entry
        presets.append(
            build_bipolar(
                category,
                label,
                neutral,
                negative,
                positive,
                default_strength,
                aliases,
            )
        )

    output = {
        "schema_version": SCHEMA_VERSION,
        "presets": presets,
    }

    out_path = os.path.join(ROOT, "presets", "default_library.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"Wrote {len(presets)} presets to {out_path}")


if __name__ == "__main__":
    main()
